# Generated by Django 5.2 on 2025-05-18 10:53

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_seat_is_booked_alter_seat_showtime_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="price",
            field=models.DecimalField(decimal_places=2, default=Decimal("79000.00"), max_digits=9),
        ),
    ]
