# Generated by Django 5.2 on 2025-05-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_seat_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.TextField(
                blank=True, help_text="Diễn viên (cách nhau bởi dấu phẩy)"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(blank=True, help_text="Đạo diễn", max_length=100),
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                blank=True, help_text="Thể loại phim", max_length=100
            ),
        ),
    ]
