# Generated by Django 5.2 on 2025-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_movie_actors_movie_director_movie_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="end_date",
            field=models.DateField(blank=True, help_text="Ngày ngừng chiếu", null=True),
        ),
    ]
